Cleans up gcc v4.6.3 -Werror=uninitialized warning and two cppcheck v1.55 warnings.  All 3 appear to be inadvertant programming errors.
gcc:
(missing curley braces)
st/st-box-layout.c: In function 'st_box_layout_allocate':
st/st-box-layout.c:802:64: error: 'next_position' may be used uninitialized in this function [-Werror=uninitialized]

cppcheck:
(missing break statement, missing asterick)
[src/cinnamon-global.c:654]: (warning) Redundant assignment of "cursor_type" in switch
[src/cinnamon-global.c:1458]: (warning, inconclusive) Using size of pointer meminfo instead of size of its data.