[a11y applet] Remove old code that causes runtime error.
    JS ERROR: !!!     message = '"this.emit is not a function"'
    JS ERROR: !!!   Exception was: TypeError: this.emit is not a function
    JS ERROR: !!!     lineNumber = '202'
    JS ERROR: !!!     fileName = '"/usr/share/cinnamon/applets/a11y@cinnamon.org/applet