Imported submodule explicitly from PIL to fix bug (#10955)
When running the Account Details app directly ($ cinnamon-settings user), user is unable to change their user picture using the "Browse for more pictures..." option. This is because the Image submodule is not automatically imported with PIL (https://stackoverflow.com/questions/11911480/python-pil-has-no-attribute-image), and produces an " AttributeError: module 'PIL' has no attribute 'Image' " on line 204. This change is already present in cinnamon-settings/modules/cs_backgrounds.py