cs-info: Don't fail with the default system-icon-path value (#11245)
The module does not open when system-icon-path value is a invalid
path, and this can cause issues because the default value
/usr/share/icons/vendor/scalable/emblems/emblem-vendor.svg does not
always presented in your system:

Using pam module (python3-pampy)
Loading Info module
Traceback (most recent call last):
  File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
    self.side_view_nav(widget, None, category)
  File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/nix/store/a8gwxrbqypfbiwxml1bmwgcf4hhp0hn3-cinnamon-common-5.4.12/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 222, in on_module_selected
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale (systemIconPath, -1, 160, True)
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/usr/share/icons/vendor/scalable/emblems/emblem-vendor.svg”: No such file or directory (4)

Let's add a try except so no matter what system-icon-path value
I set the module can still opens.