meson: Re-add dbus dependency
Fixes NixOS build by reverting part of 3295a2d63187 ("Clean up build deps and
some unused imports"):

```
../src/main.c:12:10: fatal error: dbus/dbus-shared.h: No such file or directory
   12 | #include <dbus/dbus-shared.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

A quick look this is likely needed for a few defines like

- `DBUS_NAME_FLAG_REPLACE_EXISTING`
- `DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER`
- `DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER`

in src/main.c.